
host: 'notsupreme-yoga-prod.herokuapp.com',
    connection: 'close',
        pragma: 'no-cache',
            'cache-control': 'no-cache',
                'sec-ch-ua': '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    accept: '*/*',
                        'sec-ch-ua-mobile': '?0',
                            'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36',
                                'content-type': 'application/json',
                                    origin: 'https://notsupreme-next-prod.herokuapp.com',
                                        'sec-fetch-site': 'cross-site',
                                            'sec-fetch-mode': 'cors',
                                                'sec-fetch-dest': 'empty',
                                                    referer: 'https://notsupreme-next-prod.herokuapp.com/',
                                                        'accept-encoding': 'gzip, deflate, br',
                                                            'accept-language': 'en-US,en;q=0.9',
                                                                'x-request-id': '5aed6725-0cad-4282-a2c4-60ce8ab6090b',
                                                                    'x-forwarded-for': '70.115.133.16',
                                                                        'x-forwarded-proto': 'https',
                                                                            'x-forwarded-port': '443',
                                                                                via: '1.1 vegur',
                                                                                    'connect-time': '1',
                                                                                        'x-request-start': '1610231990016',
                                                                                            'total-route-time': '0',
                                                                                                'content-length': '299'
}
{
    host: 'notsupreme-yoga-prod.herokuapp.com',
        connection: 'close',
            pragma: 'no-cache',
                'cache-control': 'no-cache',
                    'sec-ch-ua': '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                        accept: '*/*',
                            'sec-ch-ua-mobile': '?0',
                                'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36',
                                    'content-type': 'application/json',
                                        origin: 'https://notsupreme-next-prod.herokuapp.com',
                                            'sec-fetch-site': 'cross-site',
                                                'sec-fetch-mode': 'cors',
                                                    'sec-fetch-dest': 'empty',
                                                        referer: 'https://notsupreme-next-prod.herokuapp.com/',
                                                            'accept-encoding': 'gzip, deflate, br',
                                                                'accept-language': 'en-US,en;q=0.9',
                                                                    'x-request-id': '14b1e5f8-c17f-443b-ae77-4329f78eef95',
                                                                        'x-forwarded-for': '70.115.133.16',
                                                                            'x-forwarded-proto': 'https',
                                                                                'x-forwarded-port': '443',
                                                                                    via: '1.1 vegur',
                                                                                        'connect-time': '1',
                                                                                            'x-request-start': '1610231990017',
                                                                                                'total-route-time': '0',
                                                                                                    'content-length': '188'
}